# Generated by Django 5.0.7 on 2024-08-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Publication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('data_postagem', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
